services:
  postgres: 
    container_name: postgres_db
    image: postgres
    ports: 
    - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: inventory_manager
      PGDATA: /data/postgres
    volumes:
    - ./data/pg:/data/postgres