services:
  postgres:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: inventory_manager
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - app-network

  backend:
    container_name: damafashion_backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./target:/app/target
      - ./pom.xml:/app/pom.xml


networks:
  app-network:
    driver: bridge
